services:
  postgres:
    image: postgres:15
    container_name: cateringservice
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cateringservicedb_docker
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: